# -*- mode: python; -*-

# This SConscript descripts build rules for the "factk" project.
from buildscripts import *

Import("env")
Import("has_option")
Import("get_option")

env = env.Clone()

env.SConscript(dirs=['analysis','compare',
                     'web_interface', 'storage',
                     'intercom', 'objects',
                     'plugins', 'scheduler',
                     'statistic', 'unpacker'],
	       exports=['env', 'factk'])

baseEnv = env.Clone()

